# Generated by Django 4.2 on 2023-04-29 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patientid",
            name="age",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="patientid",
            name="id",
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name="patientid",
            name="phone",
            field=models.IntegerField(),
        ),
    ]
