# Generated by Django 4.2 on 2023-04-29 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mapp", "0002_alter_patientid_age_alter_patientid_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patientid",
            name="stage",
            field=models.CharField(
                choices=[
                    ("STAGE", "STAGE"),
                    ("EARLY", "EARLY"),
                    ("ADVANCED", "ADVANCED"),
                ],
                default="STAGE",
                max_length=15,
            ),
        ),
        migrations.AlterField(
            model_name="patientid",
            name="type",
            field=models.CharField(
                choices=[
                    ("TYPE", "TYPE"),
                    ("BLOOD", "BLOOD"),
                    ("BREAST", "BREAST"),
                    ("LUNG", "LUNG"),
                    ("PROSTATE", "PROSTATE"),
                    ("SKIN", "SKIN"),
                ],
                default="TYPE",
                max_length=16,
            ),
        ),
    ]
