# Generated by Django 4.2 on 2023-04-29 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mapp", "0003_alter_patientid_stage_alter_patientid_type"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="patientid",
            new_name="patient",
        ),
    ]
