# Generated by Django 4.2 on 2023-04-29 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mapp", "0004_rename_patientid_patient"),
    ]

    operations = [
        migrations.CreateModel(
            name="clinic",
            fields=[
                (
                    "cid",
                    models.IntegerField(primary_key=True, serialize=False, unique=True),
                ),
                ("cname", models.CharField(max_length=30)),
                ("cemail", models.EmailField(max_length=40)),
            ],
        ),
    ]
