# Generated by Django 4.2 on 2023-04-30 15:29

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ("mapp", "0005_clinic"),
    ]

    operations = [
        migrations.AddField(
            model_name="patient",
            name="clid",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="patient",
            name="kind",
            field=models.CharField(
                choices=[
                    ("KIND", "KIND"),
                    ("HODGKIN LYMPHOMA", "HODGKIN LYMPHOMA"),
                    ("NON-HODGKIN LYMPHOMA", "NON-HODGKIN LYMPHOMA"),
                    ("MULTIPLE LYMPHOMA", "MULTIPLE LYMPHOMA"),
                    ("NON-RECURRENT", "NON-RECURRENT"),
                    ("LOCALLY-ADVANCED", "LOCALLY-ADVANCED"),
                    ("RECURRENT", "RECURRENT"),
                    ("NON-SMALL CELL", "NON-SMALL CELL"),
                    ("SMALL CELL", "SMALL CELL"),
                    ("BASAL CELL CARCINOMA", "BASAL CELL CARCINOMA"),
                    ("SQUAMOUS CELL CARCINOMA", "SQUAMOUS CELL CARCINOMA"),
                    ("MERKEL CELL CARCINOMA", "MERKEL CELL CARCINOMA"),
                ],
                default="KIND",
                max_length=35,
            ),
        ),
        migrations.AlterField(
            model_name="patient",
            name="email",
            field=models.EmailField(max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name="patient",
            name="phone",
            field=phonenumber_field.modelfields.PhoneNumberField(
                max_length=128, region=None
            ),
        ),
        migrations.AlterField(
            model_name="patient",
            name="type",
            field=models.CharField(
                choices=[
                    ("TYPE", "TYPE"),
                    ("BLOOD", "BLOOD"),
                    ("BREAST", "BREAST"),
                    ("LUNG", "LUNG"),
                    ("PROSTATE", "PROSTATE"),
                    ("SKIN", "SKIN"),
                ],
                default="TYPE",
                max_length=15,
            ),
        ),
    ]
